"""
core/cookie_manager.py - Netscape cookies validation, sanitization, and Opener Director construction.
Supports both functional and OOP (CookieManager) interfaces.
"""

import http.cookiejar
import os
import urllib.request
from config.translations import TRANSLATIONS


def get_cookie_opener(cookie_path: str | None) -> urllib.request.OpenerDirector:
    """สร้าง urllib OpenerDirector พร้อมติดตั้ง CookieJar เมื่อมีไฟล์คุกกี้ที่ถูกต้อง"""
    if cookie_path and os.path.exists(cookie_path):
        try:
            cj = http.cookiejar.MozillaCookieJar(cookie_path)
            cj.load(ignore_discard=True, ignore_expires=True)
            return urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cj))
        except Exception:
            pass
    return urllib.request.build_opener()


def sanitize_and_save_instagram_cookies(
    src_path: str, dest_path: str, lang: str = "en"
) -> tuple[bool, str]:
    """กรองไฟล์ cookies.txt โดยคงไว้เฉพาะโดเมน Instagram, Facebook และ Threads เพื่อความปลอดภัย"""
    try:
        filtered_lines = [
            "# Netscape HTTP Cookie File\n",
            "# Generated by Instagram Pro Downloader (Sanitized)\n",
        ]
        cookie_count = 0
        valid_domains = [
            "instagram.com",
            ".instagram.com",
            "cdninstagram.com",
            ".cdninstagram.com",
            "facebook.com",
            ".facebook.com",
            "threads.net",
            ".threads.net",
        ]

        with open(src_path, "r", encoding="utf-8", errors="ignore") as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line:
                    continue

                check_line = line
                if check_line.startswith("#HttpOnly_"):
                    check_line = check_line[len("#HttpOnly_") :]
                elif check_line.startswith("#"):
                    continue

                parts = check_line.split("\t")
                if len(parts) >= 7:
                    domain = parts[0].lower()
                    if any(domain == d or domain.endswith(d) for d in valid_domains):
                        filtered_lines.append(
                            raw_line if raw_line.endswith("\n") else raw_line + "\n"
                        )
                        cookie_count += 1

        if cookie_count == 0:
            msg = TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(
                "cookie_import_fail", "No valid Instagram cookies found."
            )
            return False, msg

        os.makedirs(os.path.dirname(dest_path), exist_ok=True)
        with open(dest_path, "w", encoding="utf-8") as f:
            f.writelines(filtered_lines)

        msg_template = TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(
            "cookie_import_success", "Successfully imported {count} cookies."
        )
        return True, msg_template.format(count=cookie_count)
    except Exception as e:
        return False, f"Error: {e}"


class CookieManager:
    """Class wrapper for Cookie management providing unified access across workers and UI."""

    @staticmethod
    def get_opener(cookie_path: str | None) -> urllib.request.OpenerDirector:
        return get_cookie_opener(cookie_path)

    @staticmethod
    def sanitize_and_save(
        src_path: str, dest_path: str, lang: str = "en"
    ) -> tuple[bool, str]:
        return sanitize_and_save_instagram_cookies(src_path, dest_path, lang)

    @staticmethod
    def is_cookie_valid(cookie_path: str | None) -> bool:
        if not cookie_path or not os.path.exists(cookie_path):
            return False
        try:
            with open(cookie_path, "r", encoding="utf-8", errors="ignore") as f:
                for line in f:
                    if line.strip() and not line.startswith("#"):
                        return True
        except Exception:
            return False
        return False

    @staticmethod
    def extract_csrf_token(cookie_path: str | None) -> str | None:
        if not cookie_path or not os.path.exists(cookie_path):
            return None
        try:
            with open(cookie_path, "r", encoding="utf-8", errors="ignore") as f:
                for line in f:
                    parts = line.strip().split("\t")
                    if len(parts) >= 7 and parts[5].lower() == "csrftoken":
                        return parts[6]
        except Exception:
            pass
        return None
