"""
core/cookie_manager.py - Netscape cookies validation, sanitization, and Opener Director construction.
"""

import http.cookiejar
import os
import urllib.request
from config.translations import TRANSLATIONS


def get_cookie_opener(cookie_path: str | None) -> urllib.request.OpenerDirector:
    """สร้าง urllib OpenerDirector พร้อมติดตั้ง CookieJar เมื่อมีไฟล์คุกกี้ที่ถูกต้อง"""
    if cookie_path and os.path.exists(cookie_path):
        try:
            cj = http.cookiejar.MozillaCookieJar(cookie_path)
            cj.load(ignore_discard=True, ignore_expires=True)
            return urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cj))
        except Exception:
            pass
    return urllib.request.build_opener()


def sanitize_and_save_instagram_cookies(
    src_path: str, dest_path: str, lang: str = "th"
) -> tuple[bool, str]:
    """กรองไฟล์ cookies.txt โดยคงไว้เฉพาะโดเมน Instagram, Facebook และ Threads เพื่อความปลอดภัย"""
    try:
        filtered_lines = [
            "# Netscape HTTP Cookie File\n",
            "# Generated by Instagram Pro Downloader (Sanitized)\n",
        ]
        cookie_count = 0
        valid_domains = [
            "instagram.com",
            ".instagram.com",
            "cdninstagram.com",
            ".cdninstagram.com",
            "facebook.com",
            ".facebook.com",
            "threads.net",
            ".threads.net",
        ]

        with open(src_path, "r", encoding="utf-8", errors="ignore") as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line:
                    continue

                check_line = line
                if check_line.startswith("#HttpOnly_"):
                    check_line = check_line[len("#HttpOnly_") :]
                elif check_line.startswith("#"):
                    continue

                parts = check_line.split("\t")
                if len(parts) >= 7:
                    domain = parts[0].lower()
                    if any(domain == d or domain.endswith(d) for d in valid_domains):
                        filtered_lines.append(
                            raw_line if raw_line.endswith("\n") else raw_line + "\n"
                        )
                        cookie_count += 1

        if cookie_count == 0:
            return False, TRANSLATIONS[lang]["cookie_import_fail"]

        os.makedirs(os.path.dirname(dest_path), exist_ok=True)
        with open(dest_path, "w", encoding="utf-8") as f:
            f.writelines(filtered_lines)

        return True, TRANSLATIONS[lang]["cookie_import_success"].format(count=cookie_count)
    except Exception as e:
        return False, f"Error: {e}"